---

- hosts: k3s_cluster
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: awsmpdockereeforawsnewvpc-ddcbucket-1mpo8beyec7qg
    ansible_aws_ssm_region: eu-west-1
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: yes
  become: yes
  roles:
    - role: reset
