---

- hosts: k3s_cluster
  gather_facts: yes
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: awsmpdockereeforawsnewvpc-ddcbucket-1mpo8beyec7qg
    ansible_aws_ssm_region: eu-west-1
    ansible_python_interpreter: /usr/bin/python3
  become: yes
  roles:
    - role: prereq
    - role: download
    - role: raspberrypi

- hosts: master
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: awsmpdockereeforawsnewvpc-ddcbucket-1mpo8beyec7qg
    ansible_aws_ssm_region: eu-west-1
    ansible_python_interpreter: /usr/bin/python3
  become: yes
  roles:
    - role: k3s/master

- hosts: node
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: awsmpdockereeforawsnewvpc-ddcbucket-1mpo8beyec7qg
    ansible_aws_ssm_region: eu-west-1
    ansible_python_interpreter: /usr/bin/python3
  become: yes
  roles:
    - role: k3s/node
